import React, { createContext, useCallback, useContext, useMemo, useState } from 'react';
import { compareCart, findNearbyOptions, optimizeCart, type ApiItem, type ApiOffer, type CompareResponse } from '../lib/api';
import { ComparisonRow, GroceryItem, LocationDetails, NearbyResult, OptimizationResult, OptimizationStrategy, ProductOffer, ProviderId, ProviderOrder, ProviderSummary, SearchEngineType } from '../types';
import { DEFAULT_GROCERY_ITEMS, LOCATIONS_LIST, PROVIDERS_META } from '../data/mockData';
import { buildComparisonRows, calculateProviderSummaries, optimizeBasket } from '../lib/optimizer';
import { getItemIconType, parseGroceryInput } from '../lib/utils';

interface BasketContextType {
  currentScreen: 'home' | 'results'; setCurrentScreen: (screen: 'home' | 'results') => void;
  rawSearchInput: string; setRawSearchInput: (val: string) => void; items: GroceryItem[];
  location: LocationDetails; setLocation: (loc: LocationDetails) => void;
  searchEngine: SearchEngineType; setSearchEngine: (engine: SearchEngineType) => void;
  selectedProviders: ProviderId[]; toggleProvider: (pId: ProviderId) => void;
  comparisonRows: ComparisonRow[]; providerSummaries: ProviderSummary[]; optimizationResult: OptimizationResult;
  nearbyResult: NearbyResult | null; nearbyLoading: boolean; nearbyError: string | null; nearbyRadiusKm: number; setNearbyRadiusKm: (radius: number) => void;
  selectedStrategy: OptimizationStrategy; setSelectedStrategy: (strategy: OptimizationStrategy) => void;
  isOptimizationModalOpen: boolean; setIsOptimizationModalOpen: (open: boolean) => void;
  isLocationModalOpen: boolean; setIsLocationModalOpen: (open: boolean) => void;
  isLoadingSearch: boolean; searchError: string | null; compareStatus: string | null;
  addItem: (name: string, quantity?: number, unit?: string) => void; removeItem: (id: string) => void;
  updateItemQuantity: (id: string, qty: number) => void; handleSearchSubmit: (customText?: string) => void;
  loadPreset: (presetItemsText: string) => void; resetToDefault: () => void;
}

const BasketContext = createContext<BasketContextType | undefined>(undefined);

function toUiItems(apiItems: ApiItem[]): GroceryItem[] { return apiItems.map((item) => ({ id: item.id, rawInput: item.rawText, name: item.name, quantity: item.quantity ?? 1, unit: item.unit ?? 'unspecified', iconType: getItemIconType(item.name) })); }
function toUiOffer(offer: ApiOffer, item: GroceryItem): ProductOffer { return { provider: offer.providerId as ProviderId, productId: offer.productId ?? offer.id, title: offer.title, price: offer.price ?? 0, originalPrice: offer.oldPrice ?? undefined, quantity: offer.packQuantity ?? item.quantity, unit: offer.packUnit ?? item.unit, url: offer.productUrl ?? '#', available: offer.available && offer.price !== null }; }

function mapRows(api: CompareResponse['data'], selectedProviders: ProviderId[]): ComparisonRow[] {
  return api.items.map((apiItem) => { const item = toUiItems([apiItem])[0]; const offers: Record<ProviderId, ProductOffer | null> = { blinkit: null, zepto: null, instamart: null, bbnow: null }; apiItem.offers.forEach((offer) => { if (selectedProviders.includes(offer.providerId as ProviderId)) offers[offer.providerId as ProviderId] = toUiOffer(offer, item); }); const available = selectedProviders.map((provider) => offers[provider]).filter((offer): offer is ProductOffer => Boolean(offer?.available)); const lowest = [...available].sort((a, b) => a.price - b.price)[0]; return { item, offers, lowestPrice: lowest?.price ?? null, lowestProvider: lowest?.provider ?? null, priceSpread: available.length > 1 ? Math.max(...available.map((offer) => offer.price)) - Math.min(...available.map((offer) => offer.price)) : 0 }; });
}

function mapSummaries(rows: ComparisonRow[], api: CompareResponse['data'], selectedProviders: ProviderId[]): ProviderSummary[] {
  return selectedProviders.map((provider) => { const providerOffers = api.items.flatMap((item) => item.offers.filter((offer) => offer.providerId === provider && offer.available && offer.price !== null)); const itemTotal = providerOffers.reduce<number>((sum, offer) => sum + (offer.price ?? 0), 0); const missingItems = rows.filter((row) => !row.offers[provider]?.available).map((row) => row.item); const fees = providerOffers.map((offer) => offer.deliveryFee); const deliveryFee = fees.some((fee) => fee === null) ? null : fees.reduce<number>((sum, fee) => sum + (fee ?? 0), 0); return { provider, name: PROVIDERS_META[provider]?.name ?? provider, itemsFound: rows.length - missingItems.length, totalItems: rows.length, itemTotal, deliveryFee, handlingFee: null, estimatedTotal: itemTotal + (deliveryFee ?? 0), isCompleteBasket: missingItems.length === 0, missingItems }; }).map((summary, _, all) => ({ ...summary, isCheapestOverall: summary.isCompleteBasket && all.filter((candidate) => candidate.isCompleteBasket).sort((a, b) => a.estimatedTotal - b.estimatedTotal)[0]?.provider === summary.provider }));
}

function strategyToApi(strategy: OptimizationStrategy): { strategy: 'LOWEST_TOTAL' | 'BEST_VALUE' | 'BEST_DEALS'; maxProviders: number } { if (strategy === 'lowest_product_price') return { strategy: 'LOWEST_TOTAL', maxProviders: 3 }; if (strategy === 'single_store_best') return { strategy: 'BEST_VALUE', maxProviders: 1 }; if (strategy === 'minimize_delivery_fees') return { strategy: 'BEST_VALUE', maxProviders: 2 }; return { strategy: 'BEST_VALUE', maxProviders: 2 }; }

export function BasketProvider({ children }: { children: React.ReactNode }) {
  const [currentScreen, setCurrentScreen] = useState<'home' | 'results'>('home');
  const [rawSearchInput, setRawSearchInput] = useState('atta 5kg, rice 2kg, milk 1L, eggs 12, bread');
  const [items, setItems] = useState<GroceryItem[]>(DEFAULT_GROCERY_ITEMS);
  const [location, setLocation] = useState<LocationDetails>(LOCATIONS_LIST[0]);
  const [searchEngine, setSearchEngine] = useState<SearchEngineType>('google_shopping');
  const [selectedProviders, setSelectedProviders] = useState<ProviderId[]>(['blinkit', 'zepto', 'instamart']);
  const [selectedStrategyState, setSelectedStrategyState] = useState<OptimizationStrategy>('split_lowest_cost');
  const [isOptimizationModalOpen, setIsOptimizationModalOpen] = useState(false); const [isLocationModalOpen, setIsLocationModalOpen] = useState(false); const [isLoadingSearch, setIsLoadingSearch] = useState(false); const [searchError, setSearchError] = useState<string | null>(null); const [compareStatus, setCompareStatus] = useState<string | null>(null); const [apiData, setApiData] = useState<CompareResponse['data'] | null>(null); const [nearbyResult, setNearbyResult] = useState<NearbyResult | null>(null); const [nearbyLoading, setNearbyLoading] = useState(false); const [nearbyError, setNearbyError] = useState<string | null>(null); const [nearbyRadiusKmState, setNearbyRadiusKmState] = useState(2);
  const [optimizationResult, setOptimizationResult] = useState<OptimizationResult>(optimizeBasket(buildComparisonRows(DEFAULT_GROCERY_ITEMS, ['blinkit', 'zepto', 'instamart']), 'split_lowest_cost', ['blinkit', 'zepto', 'instamart']));
  const comparisonRows = useMemo(() => apiData ? mapRows(apiData, selectedProviders) : buildComparisonRows(items, selectedProviders), [apiData, items, selectedProviders]);
  const providerSummaries = useMemo(() => apiData ? mapSummaries(comparisonRows, apiData, selectedProviders) : calculateProviderSummaries(comparisonRows, selectedProviders), [apiData, comparisonRows, selectedProviders]);

  const runOptimization = useCallback(async (data: CompareResponse['data'], strategy: OptimizationStrategy) => { try { const mode = strategyToApi(strategy); const result = await optimizeCart({ strategy: mode.strategy, constraints: { maxProviders: mode.maxProviders, allowSubstitutes: false, allowOverbuy: false }, items: data.items, offers: data.offers }); const recommended = result.data.recommendedBasket; const uiItems = toUiItems(data.items); const orders: ProviderOrder[] = result.data.orders.map((order) => ({ provider: order.providerId as ProviderId, providerName: order.providerName, items: order.items.map((line) => { const item = uiItems.find((candidate) => candidate.id === line.itemId) ?? uiItems[0]; return { item, offer: toUiOffer(data.offers.find((offer) => offer.id === line.offerId)!, item) }; }), subtotal: order.items.reduce((sum, line) => sum + line.lineTotal, 0), deliveryFee: 0, handlingFee: 0, total: order.items.reduce((sum, line) => sum + line.lineTotal, 0) })); setOptimizationResult({ strategy, strategyTitle: strategy === 'split_lowest_cost' ? 'Best Value Basket' : strategy, strategyDescription: 'Calculated by the BlinkBargain backend from observed offers.', estimatedTotal: recommended?.estimatedTotal ?? 0, singleStoreBaselineTotal: recommended ? recommended.estimatedTotal + (recommended.savings ?? 0) : 0, savings: recommended?.savings ?? 0, savingsPercent: 0, providerCount: recommended?.providerCount ?? 0, orders, rationale: [...result.data.reasoning.facts, ...result.data.reasoning.tradeoffs, ...result.data.warnings.map((warning) => warning.message)], coveragePercent: recommended ? 100 : 0 }); } catch (error) { setSearchError(error instanceof Error ? error.message : 'Optimization failed.'); } }, []);
  const runNearby = useCallback(async (data: CompareResponse['data'], radiusKm: number) => { setNearbyLoading(true); setNearbyError(null); try { const result = await findNearbyOptions({ location: { text: data.location.text, pinCode: data.location.pinCode, ...(location as unknown as { latitude?: number; longitude?: number }) }, radiusKm, items: data.items, offers: data.offers }); setNearbyResult(result.data); } catch (error) { setNearbyResult(null); setNearbyError(error instanceof Error ? error.message : 'Nearby store search unavailable.'); } finally { setNearbyLoading(false); } }, [location]);
  const setSelectedStrategy = useCallback((strategy: OptimizationStrategy) => { setSelectedStrategyState(strategy); if (apiData) { if (strategy === 'nearby_cheaper') void runNearby(apiData, nearbyRadiusKmState); else void runOptimization(apiData, strategy); } }, [apiData, nearbyRadiusKmState, runNearby, runOptimization]);
  const setNearbyRadiusKm = useCallback((radius: number) => { setNearbyRadiusKmState(radius); if (apiData && selectedStrategyState === 'nearby_cheaper') void runNearby(apiData, radius); }, [apiData, runNearby, selectedStrategyState]);
  const toggleProvider = useCallback((pId: ProviderId) => setSelectedProviders((prev) => prev.includes(pId) ? (prev.length <= 1 ? prev : prev.filter((id) => id !== pId)) : [...prev, pId]), []);
  const addItem = useCallback((name: string, quantity = 1, unit = '1 pc') => { const parsed = parseGroceryInput(`${name} ${unit}`); if (parsed.length) setItems((prev) => [...prev, parsed[0]]); }, []);
  const removeItem = useCallback((id: string) => setItems((prev) => prev.filter((item) => item.id !== id)), []);
  const updateItemQuantity = useCallback((id: string, qty: number) => { if (qty <= 0) return removeItem(id); setItems((prev) => prev.map((item) => item.id === id ? { ...item, quantity: qty } : item)); }, [removeItem]);
  const handleSearchSubmit = useCallback(async (customText?: string) => { const text = customText ?? rawSearchInput; if (!text.trim()) return; const parsed = parseGroceryInput(text); if (!parsed.length) return; setRawSearchInput(text); setIsLoadingSearch(true); setSearchError(null); setNearbyResult(null); setNearbyError(null); setCompareStatus('searching'); try { const response = await compareCart({ location: { text: location.formatted || `${location.city}, ${location.pinCode}`, pinCode: location.pinCode }, items: parsed.map((item) => ({ name: item.name, quantity: item.quantity, unit: item.unit.replace(/[0-9.\s]/g, '') || null })), providers: selectedProviders.filter((provider) => provider !== 'bbnow') }); setApiData(response.data); setItems(toUiItems(response.data.items)); setCompareStatus(response.status); setCurrentScreen('results'); if (selectedStrategyState === 'nearby_cheaper') await runNearby(response.data, nearbyRadiusKmState); else await runOptimization(response.data, selectedStrategyState); window.scrollTo({ top: 0, behavior: 'smooth' }); } catch (error) { setSearchError(error instanceof Error ? error.message : 'Price comparison failed.'); setCompareStatus(null); } finally { setIsLoadingSearch(false); } }, [location, nearbyRadiusKmState, rawSearchInput, runNearby, runOptimization, selectedProviders, selectedStrategyState]);
  const loadPreset = useCallback((text: string) => { setRawSearchInput(text); void handleSearchSubmit(text); }, [handleSearchSubmit]); const resetToDefault = useCallback(() => { setApiData(null); setItems(DEFAULT_GROCERY_ITEMS); setRawSearchInput('atta 5kg, rice 2kg, milk 1L, eggs 12, bread'); setCurrentScreen('home'); setSearchError(null); }, []);
  return <BasketContext.Provider value={{ currentScreen, setCurrentScreen, rawSearchInput, setRawSearchInput, items, location, setLocation, searchEngine, setSearchEngine, selectedProviders, toggleProvider, comparisonRows, providerSummaries, optimizationResult, nearbyResult, nearbyLoading, nearbyError, nearbyRadiusKm: nearbyRadiusKmState, setNearbyRadiusKm, selectedStrategy: selectedStrategyState, setSelectedStrategy, isOptimizationModalOpen, setIsOptimizationModalOpen, isLocationModalOpen, setIsLocationModalOpen, isLoadingSearch, searchError, compareStatus, addItem, removeItem, updateItemQuantity, handleSearchSubmit, loadPreset, resetToDefault }}>{children}</BasketContext.Provider>;
}

export function useBasket() { const context = useContext(BasketContext); if (!context) throw new Error('useBasket must be used within a BasketProvider'); return context; }
