export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_LOCATION: "INVALID_LOCATION",
  EMPTY_BASKET: "EMPTY_BASKET",
  TOO_MANY_ITEMS: "TOO_MANY_ITEMS",
  TOO_MANY_PROVIDERS: "TOO_MANY_PROVIDERS",
  SERPAPI_CONFIGURATION_ERROR: "SERPAPI_CONFIGURATION_ERROR",
  SERPAPI_AUTH_ERROR: "SERPAPI_AUTH_ERROR",
  SERPAPI_RATE_LIMIT: "SERPAPI_RATE_LIMIT",
  SERPAPI_TIMEOUT: "SERPAPI_TIMEOUT",
  SERPAPI_UPSTREAM_ERROR: "SERPAPI_UPSTREAM_ERROR",
  SERPAPI_BAD_RESPONSE: "SERPAPI_BAD_RESPONSE",
  SERPAPI_TEMPORARILY_UNAVAILABLE: "SERPAPI_TEMPORARILY_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;
